package functions

import "mattwach/rpngo/rpn"

// RegisterAll resisters functions that are core to the RPN engine. There
// are other functions, such as window-specific functions, that will be
// added by their respective owners as the functions module should not
// know about these.
func RegisterAll(rpn *rpn.RPN) {
	rpn.Register("@", Exec, ExecHelp)
	rpn.Register("-", Subtract, SubtractHelp)
	rpn.Register("!=", NotEqual, NotEqualHelp)
	rpn.Register("*", Multiply, MultiplyHelp)
	rpn.Register("/", Divide, DivideHelp)
	rpn.Register("+", Add, AddHelp)
	rpn.Register("<", LessThan, LessThanHelp)
	rpn.Register("<=", LessThanEqual, LessThanEqualHelp)
	rpn.Register("=", Equal, EqualHelp)
	rpn.Register(">", GreaterThan, GreaterThanHelp)
	rpn.Register(">=", GreaterThanEqual, GreaterThanEqualHelp)
	rpn.Register("a", Add, AddHelp)
	rpn.Register("bin", Bin, BinHelp)
	rpn.Register("c", Copy, CopyHelp)
	rpn.Register("ci", CopyIndex, CopyIndexHelp)
	rpn.Register("cos", Cos, CosHelp)
	rpn.Register("d", Divide, DivideHelp)
	rpn.Register("float", Float, FloatHelp)
	rpn.Register("if", If, IfHelp)
	rpn.Register("ifelse", IfElse, IfElseHelp)
	rpn.Register("input", Input, InputHelp)
	rpn.Register("int", Int, IntHelp)
	rpn.Register("for", For, ForHelp)
	rpn.Register("hex", Hex, HexHelp)
	rpn.Register("load", Load, LoadHelp)
	rpn.Register("m", Multiply, MultiplyHelp)
	rpn.Register("mi", MoveIndex, MoveIndexHelp)
	rpn.Register("noop", NoOp, NoOpHelp)
	rpn.Register("neg", Negate, NegateHelp)
	rpn.Register("oct", Oct, OctHelp)
	rpn.Register("print", Print, PrintHelp)
	rpn.Register("printall", PrintAll, PrintAllHelp)
	rpn.Register("println", Println, PrintlnHelp)
	rpn.Register("printlnx", PrintlnX, PrintlnXHelp)
	rpn.Register("prints", PrintS, PrintSHelp)
	rpn.Register("printsx", PrintSX, PrintSXHelp)
	rpn.Register("printx", PrintX, PrintXHelp)
	rpn.Register("rand", Rand, RandHelp)
	rpn.Register("s", Subtract, SubtractHelp)
	rpn.Register("sin", Sin, SinHelp)
	rpn.Register("sq", Square, SquareHelp)
	rpn.Register("sqrt", SquareRoot, SquareRootHelp)
	rpn.Register("str", Str, StrHelp)
	rpn.Register("sw", Swap, SwapHelp)
	rpn.Register("tan", Tan, TanHelp)
	rpn.Register("x", Drop, DropHelp)
	rpn.Register("X", DropAll, DropAllHelp)
	rpn.Register("xi", DropIndex, DropIndexHelp)
}
